# Generated by Django 2.2.24 on 2022-02-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_flat_new_building"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flat",
            old_name="new_building",
            new_name="is_new_building",
        ),
    ]
