# Generated by Django 2.2.24 on 2022-02-10 13:24

from django.db import migrations


def populate_new_building_field(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")

    for flat in Flat.objects.all():
        flat.is_new_building = True if flat.construction_year >= 2015 else False
        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0003_flat_new_building"),
    ]

    operations = [
        migrations.RunPython(populate_new_building_field),
    ]
