# Generated by Django 2.2.24 on 2022-02-12 08:32
import phonenumbers
from django.db import migrations


def normalize_phone_number(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")

    for flat in Flat.objects.all():
        owner_pure_phone = phonenumbers.parse(flat.owners_phonenumber, "RU")

        if phonenumbers.is_valid_number(owner_pure_phone):
            flat.owner_pure_phone = owner_pure_phone
        else:
            flat.owner_pure_phone = None

        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0011_auto_20220212_1132"),
    ]

    operations = [
        migrations.RunPython(normalize_phone_number),
    ]
