# Generated by Django 2.2.24 on 2022-02-12 09:38

from django.db import migrations


def populate_owners_from_flats(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    Owner = apps.get_model("property", "Owner")

    for flat in Flat.objects.all():
        Owner.objects.get_or_create(
            fullname=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phone=flat.owner_pure_phone,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0013_owner"),
    ]

    operations = [
        migrations.RunPython(populate_owners_from_flats),
    ]
